/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Register$Params } from './fn/auth-controller/register';
export { register } from './fn/auth-controller/register';
export type { Authenticate$Params } from './fn/auth-controller/authenticate';
export { authenticate } from './fn/auth-controller/authenticate';
export type { Confirm$Params } from './fn/auth-controller/confirm';
export { confirm } from './fn/auth-controller/confirm';
